//! The registry as it is today, over the network.
//!
//! Ignored by default, because `cargo test` is a statement about this code and
//! this file is a statement about GitHub. It earns its place because those two
//! can disagree without anybody touching the repository: release assets moved
//! to another storage host once already, and every unit test stayed green while
//! not one extension would install.
//!
//! Run it after touching `registry.rs`, and when an install fails for a reason
//! the window cannot explain:
//!
//! ```text
//! cargo test -p sync-extensions --test live_registry -- --ignored --nocapture
//! ```
#![allow(clippy::expect_used)]

use sync_extensions::{Archive, Registry};

/// Fetches the published index, downloads every artefact, and opens each one.
///
/// Every rule in `registry.rs` is on this path: the index host, the pin to a
/// release of the organisation, each redirect hop, the ceiling on the download
/// and the digest. A failure names which one gave way — the error carries the
/// host or the URL that was refused.
///
/// It opens what it downloaded, and that is not a flourish. A published archive
/// once matched its digest exactly and would not open, because the packer left
/// out a file the manifest declared; the download was checked everywhere and
/// the step after it nowhere, so the marketplace was broken while every test
/// was green. Every extension rather than one, for the same reason — the two
/// that were broken were the two with a stylesheet.
#[test]
#[ignore = "talks to GitHub"]
fn every_published_extension_downloads_and_opens() {
    let dir = tempfile::tempdir().expect("a directory to fetch into");
    let registry = Registry::at(dir.path().to_path_buf());

    let fetched = registry.index().expect("the index is reachable");
    assert!(
        !fetched.answer.extensions.is_empty(),
        "the published index lists nothing"
    );

    for listed in &fetched.answer.extensions {
        let file = registry
            .download(&listed.artefact, dir.path())
            .unwrap_or_else(|error| panic!("{} did not download: {error}", listed.id));

        let written = std::fs::metadata(&file)
            .expect("the artefact was written")
            .len();
        assert_eq!(
            written, listed.artefact.bytes,
            "{} arrived at another size",
            listed.id
        );

        // The step that used to be nobody's: bytes that hash correctly and are
        // still not a package this build can install.
        let archive = Archive::open(&file, None)
            .unwrap_or_else(|error| panic!("{} downloaded and would not open: {error}", listed.id));
        assert_eq!(
            archive.manifest().version,
            listed.version,
            "{} is indexed at another version than it carries",
            listed.id
        );
    }
}

/// Every extension the index lists has a ledger, and the two agree.
///
/// The index says what the newest version is; the ledger says what every
/// version was and what changed in it, and an update is offered by reading the
/// first and explained by reading the second. Nothing in this repository can
/// tell whether those two files agree — they are generated by another
/// repository's CI, published as two artefacts, and a ledger that was not
/// regenerated with the index it belongs to is exactly the shape of failure
/// this file exists for: the marketplace would offer a version and have nothing
/// to say about it, or name a file the index never mentioned.
#[test]
#[ignore = "talks to GitHub"]
fn every_indexed_version_is_in_its_own_ledger() {
    let dir = tempfile::tempdir().expect("a directory to fetch into");
    let registry = Registry::at(dir.path().to_path_buf());

    let fetched = registry.index().expect("the index is reachable");
    for listed in &fetched.answer.extensions {
        let ledger = registry
            .ledger(&listed.id)
            .unwrap_or_else(|error| panic!("{} has no readable ledger: {error}", listed.id));

        assert_eq!(ledger.answer.id, listed.id, "the ledger is somebody else's");

        let newest = ledger
            .answer
            .versions
            .iter()
            .find(|release| release.version == listed.version)
            .unwrap_or_else(|| {
                panic!(
                    "{} is indexed at {} and its ledger does not carry that version",
                    listed.id, listed.version,
                )
            });

        // The same file from both directions. A digest that disagrees means one
        // of the two was regenerated without the other, and an update applied
        // from the ledger would then not be the artefact the index named.
        assert_eq!(
            newest.artefact.sha256, listed.artefact.sha256,
            "{} is published as two different files",
            listed.id,
        );
    }
}
