#!/usr/bin/env node
/**
 * Copies the extension contract to where packages are built against it.
 *
 *   node scripts/api-publish.mjs [<extensions repo>]
 *
 * Two files, and they are the whole of what an author outside this repository
 * needs: the rolled-up declarations, which say what may be named, and the list
 * of which of those names exist at runtime, which is what the extension build's
 * shim binds to the host's objects.
 *
 * The second cannot be derived from the first by anything downstream. A `.d.ts`
 * describes types and values in the same grammar, and a shim that guessed would
 * either bind interfaces — producing `undefined` where a component was expected
 * — or miss functions. It is derived *here*, where the compiler's own output is
 * at hand, and travels with the declarations it was derived from.
 *
 * It writes into `@sync-buzz/extension-api`'s own repository, which is where both
 * files are committed and published from. That package carries the contract and
 * the tools; this repository carries the implementation the contract describes.
 * The two are deliberately not one: an extension has to be buildable against a
 * *stated version* of the surface, and a package that read Sync's source would
 * be buildable only against whatever the neighbour happened to be doing.
 */

import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const into = resolve(process.argv[2] ?? join(root, "../sync-extension-api"));

const rollup = join(root, "temp/extension-api.d.ts");
if (!existsSync(rollup)) {
  process.stderr.write("No rollup yet. Run `pnpm api:check` first.\n");
  process.exit(1);
}

const version = /SYNC_API_VERSION = "([^"]+)"/.exec(
  readFileSync(join(root, "src/lib/extension-api/version.ts"), "utf8"),
)?.[1];

/**
 * The names that exist at runtime, as the declarations spell them.
 *
 * `function`, `const` and `class` are values; `interface` and `type` are not,
 * and binding one of those would put `undefined` on the surface under a name
 * that type-checks. `enum` is deliberately absent because nothing on the
 * surface is one — if that changes, this refuses rather than guesses.
 */
const declarations = readFileSync(rollup, "utf8");
const values = [
  ...declarations.matchAll(/^export declare (function|const|class) (\w+)/gm),
].map((match) => match[2]);

const enums = [...declarations.matchAll(/^export declare (?:const )?enum (\w+)/gm)];
if (enums.length > 0) {
  process.stderr.write(
    `The surface has an enum (${enums.map((m) => m[1]).join(", ")}), which this script does not know how to bind.\n`,
  );
  process.exit(1);
}

/**
 * The theme, as an extension's own build needs to see it.
 *
 * An extension writes `bg-panel` and `gap-1.5` like the shell does, and its
 * Tailwind has to know those names exist. What it must **not** know is what
 * they are worth: the block is declared `@theme inline`, so a utility compiles
 * to `background-color: var(--surface-panel)` and the value is read from the
 * window's own `:root` at paint. An extension therefore carries no colour, no
 * spacing step and no radius — only the rules its own markup uses — and
 * retinting the window retints every extension in it without one of them being
 * rebuilt or republished.
 *
 * Lifted out of `globals.css` rather than written twice, for the reason the
 * whole of this script exists: a second copy is a copy that was true when it
 * was last edited.
 */
const stylesheet = readFileSync(
  join(root, "src/app/globals.css"),
  "utf8",
);
const opened = stylesheet.indexOf("@theme inline {");
if (opened === -1) {
  process.stderr.write(
    "globals.css has no `@theme inline` block, so there is no theme to publish.\n",
  );
  process.exit(1);
}

// Braces rather than the first `}`: the block contains none today and would be
// cut in half by the first one somebody nests.
let depth = 0;
let closed = -1;
for (let at = opened; at < stylesheet.length; at += 1) {
  if (stylesheet[at] === "{") depth += 1;
  if (stylesheet[at] === "}") {
    depth -= 1;
    if (depth === 0) {
      closed = at + 1;
      break;
    }
  }
}
if (closed === -1) {
  process.stderr.write("The `@theme inline` block in globals.css is not closed.\n");
  process.exit(1);
}

const theme = [
  "/*",
  " * The Sync theme, as an extension compiles against it.",
  " *",
  " * GENERATED by `pnpm api:publish` in the Sync repository, from the",
  " * `@theme inline` block of `src/app/globals.css`. Do not edit: the next",
  " * publish overwrites it.",
  " *",
  " * `inline` is the whole point. Every name here resolves to a `var()` that",
  " * the window defines on `:root`, so a utility built from this stylesheet",
  " * carries a reference and never a value. That is what keeps one design",
  " * system in one place while every extension compiles its own rules.",
  " */",
  "",
  stylesheet.slice(opened, closed),
  "",
].join("\n");

mkdirSync(join(into, "types"), { recursive: true });
copyFileSync(rollup, join(into, "types/index.d.ts"));
writeFileSync(join(into, "theme.css"), theme);
writeFileSync(
  join(into, "runtime.json"),
  `${JSON.stringify({ version, values: [...new Set(values)].sort() }, null, 2)}\n`,
);

// The package's own version is the surface's version. There is nothing else it
// could be: what it publishes is the surface, and a second number beside the
// first would be one more thing to keep in step.
const manifest = join(into, "package.json");
const stated = JSON.parse(readFileSync(manifest, "utf8"));
if (stated.version !== version) {
  stated.version = version;
  writeFileSync(manifest, `${JSON.stringify(stated, null, 2)}\n`);
}

process.stdout.write(
  `Contract ${version} published to ${into} — ${values.length} runtime exports.\n`,
);
