//! What a package says about itself.
//!
//! The manifest is the whole of what the host knows before it runs anything, so
//! every question the window asks at install time has to be answerable from
//! this file alone: what sections it brings, what types it publishes, what it
//! needs from the build, what it opens.
//!
//! JSON rather than TOML because four things read it — the packer, the
//! registry's CI, this crate and the window — and one schema validates it for
//! all of them. A TOML manifest would mean a second parser inside the webview
//! and a schema that is prose.
//!
//! **Unknown fields are refused.** The manifest is generated by a tool, so a
//! field nobody recognises is a typo or a newer format, and both are better as
//! a refusal naming the field than as a silently ignored line. What makes that
//! safe rather than brittle is [`Manifest::manifest_version`]: a genuinely newer
//! format says so in one number, and the refusal for that says which build is
//! too old rather than pointing at a field.

use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};

/// The capability a package needs before this build will run its handlers.
///
/// Named here as well as on the surface that publishes it
/// (`src/lib/extension-api/version.ts`) because this is the one rule about it
/// that is a property of the *manifest* rather than of the build: a package
/// that ships handlers and does not ask for them is inconsistent with itself,
/// and that is answerable without knowing anything about the host. Whether the
/// host *has* the capability is the host's question, and it is asked where the
/// rest of them are.
pub const BACKGROUND_CAPABILITY: &str = "background";

/// The capability a package needs before this build will put it on the clock.
///
/// Separate from [`BACKGROUND_CAPABILITY`] because it is a separate agreement:
/// running a handler when somebody installs a package is a thing they watched
/// happen, and running one at three in the morning on a machine with no window
/// open is not. A package that wants both asks for both.
pub const SCHEDULE_CAPABILITY: &str = "schedule";

/// The capability a package needs before this build will dial out for it.
///
/// The third of the same kind, and the one a person has most reason to be told
/// about: the other two are about *when* a package's own code runs, and this is
/// about a package reading something nobody in this window wrote. What it may
/// reach is [`Net::hosts`] — the capability is the agreement, the list is its
/// extent, and neither is any use without the other.
pub const NET_CAPABILITY: &str = "net";

/// The manifest format this build reads.
///
/// Bumped when the *shape* changes incompatibly, which is a different question
/// from the extension API's version: one is how the file is written, the other
/// is what the code inside may call.
pub const SUPPORTED_MANIFEST_VERSION: u32 = 1;

/// Something wrong with a manifest, in words a person can act on.
#[derive(Debug, thiserror::Error)]
pub enum ManifestError {
    #[error("the manifest is not readable JSON: {0}")]
    Unreadable(#[from] serde_json::Error),
    #[error(
        "this extension needs a newer Sync: its manifest is written in format {found}, and this build reads {SUPPORTED_MANIFEST_VERSION}"
    )]
    Newer { found: u32 },
    #[error("the manifest is missing something it cannot do without: {0}")]
    Incomplete(String),
    #[error("{0}")]
    Invalid(String),
}

/// What the host must be able to do before the package is worth loading.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct Engines {
    /// A semver range over the host's `SYNC_API_VERSION`, such as `^1.2`.
    ///
    /// Not checked here, and that is deliberate: `SYNC_API_VERSION` is declared
    /// in `src/lib/extension-api/version.ts` and belongs to the surface it
    /// describes. Checking it in Rust as well would mean the number lives in
    /// two places, and the day they disagree the answer would depend on which
    /// one refused first.
    pub sync_api: String,
}

/// Where a package may reach, and the whole of what it may reach.
///
/// The list is the permission. [`NET_CAPABILITY`] is a person agreeing that
/// this package talks to something outside the window; this is what they were
/// shown when they agreed, and the request that names anything else is refused
/// before it leaves the machine.
///
/// **No pattern, no wildcard, no scheme.** Each entry is exactly one host, as a
/// URL spells it. `*.example.com` would be a package asking for a family nobody
/// enumerated — and it is the shape every allow-list is eventually widened by,
/// because one host that needs it is indistinguishable in the manifest from a
/// thousand that do not. A package that genuinely needs two hosts writes two.
#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct Net {
    /// The hosts, and empty is a package that reaches nothing.
    #[serde(default)]
    pub hosts: Vec<String>,
}

impl Net {
    /// Whether a host is one this package declared.
    ///
    /// Compared without case, because a host name has none: `API.GitHub.com`
    /// and `api.github.com` are one host, and a check that told them apart
    /// would refuse a request over the shape of a string.
    #[must_use]
    pub fn admits(&self, host: &str) -> bool {
        self.hosts
            .iter()
            .any(|declared| declared.eq_ignore_ascii_case(host))
    }
}

/// One section the extension contributes to the window.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct Area {
    /// Unique within the extension. The window addresses it as `<ext>/<id>`.
    pub id: String,
    /// What the sidebar calls it.
    pub label: String,
    /// What the section is for, where a column needs explaining.
    #[serde(default)]
    pub description: String,
    /// One of the shapes the shell draws: `browse`, `list`, `detail`, `single`.
    ///
    /// A string rather than an enum, and checked against the host's own list
    /// rather than this one: the set of frames belongs to the shell, and a
    /// second copy of it here would be a second thing to keep in step.
    pub frame: String,
    /// A name from the shared icon library, resolved by the host at load.
    #[serde(default)]
    pub icon: Option<String>,
    /// What the host counts and draws on this section's row, if anything.
    #[serde(default)]
    pub badge: Option<Badge>,
}

/// A question about the corpus, asked of the host and drawn on an area's row.
///
/// Declared rather than reported, and that is the whole reason it exists beside
/// the runtime channel: an area is mounted on first visit, so a badge that only
/// a mounted area could raise would be silent in exactly the case a person most
/// needs it — the first launch after opening a project. Nothing here runs a line
/// of the package.
///
/// It is deliberately not a general query language. What the engine answers in
/// one call is a listing's counts by kind under a freshness filter, and that is
/// what this is: anything wider would be a query the host had to interpret, and
/// a badge is not worth a second dialect of asking.
#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct Badge {
    /// Which kinds are counted, and empty is every kind this section opens.
    ///
    /// Empty is the answer for almost every extension, because a badge on a
    /// section is about the records that section shows and the manifest has
    /// already said which those are. Naming them is for the extension with two
    /// sections over one vocabulary: [`Opens`] belongs to the package and could
    /// not tell them apart.
    ///
    /// Each one is prefixed with the extension's id, by the rule [`Opens::kinds`]
    /// already reads: a badge counting somebody else's records is a number
    /// nobody can act on, and it would be one extension making a claim about
    /// another's data.
    #[serde(default)]
    pub kinds: Vec<String>,
    /// Which freshness states are counted, and empty is every state.
    ///
    /// A string rather than an enum, and checked against the host's own list
    /// rather than this one, for the reason [`Area::frame`] is: the states are
    /// the engine's, and a second copy of them here would be a second thing to
    /// keep in step.
    #[serde(default)]
    pub freshness: Vec<String>,
}

/// Which records this extension knows how to show.
#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct Opens {
    /// Kinds it opens, which are normally the kinds it publishes.
    #[serde(default)]
    pub kinds: Vec<String>,
    /// Whether it opens the types the project made itself.
    ///
    /// This is the field that retires `PROJECT_TYPES = "records"` from the
    /// shell. Exactly one installed extension should claim it; the host takes
    /// the first that does and says so when two do, because a project whose own
    /// types open in one section on Monday and another on Tuesday is worse than
    /// a warning.
    #[serde(default)]
    pub project_types: bool,
}

/// What the extension needs fetched before it works well.
#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct Dependencies {
    /// Packages from npm, by name. Retires `FETCHES_DEPENDENCIES = {"chat"}`.
    #[serde(default)]
    pub npm: Vec<String>,
}

/// What it needs from the project rather than from the build.
#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct Requires {
    /// Other extensions, as `id@range`.
    #[serde(default)]
    pub extensions: Vec<String>,
}

/// Who made it, for the inspector.
#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct Author {
    pub name: String,
    #[serde(default)]
    pub url: Option<String>,
}

/// When the host calls a handler because something happened to the package
/// itself, rather than because a clock struck or another extension asked.
///
/// Each is a name in the package's service module. There is one for now, and
/// the shape is an object rather than a list so that adding *removed* or
/// *project opened* is a field rather than a convention about ordering.
#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct Lifecycle {
    /// Called once, when the package is installed into a project.
    ///
    /// Chosen as the first occasion because it is the one with a person in
    /// front of it: it is synchronous, it has somewhere to report a failure,
    /// and a handler that fails here fails the install and says why. A clock
    /// firing at three in the morning has none of those.
    #[serde(default)]
    pub installed: Option<String>,
}

/// A handler the clock calls, and how often it is called.
///
/// Interval rather than cron, by `docs/background.md` §4.1: a syntax that can
/// say *at 03:00 on weekdays* has bought a timezone question and a
/// missed-while-asleep question, and nothing here needs either.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct Scheduled {
    /// A name in the package's service module.
    pub handler: String,
    /// What this handler does, in the author's own words.
    ///
    /// **Required, unlike [`Area::description`]**, and the difference is that
    /// an area has a label a person reads instead. A scheduled handler has
    /// nothing else readable: its name is the package's internal name for one
    /// of its own functions and is deliberately not shown, so without this the
    /// page could only say *runs every 6h* and leave *runs what* unanswered —
    /// to somebody deciding whether to let it run while they are asleep.
    ///
    /// The host writes the cadence beside it and never takes it from here, so
    /// this sentence cannot disagree with [`Scheduled::every`] about how often
    /// anything happens.
    pub description: String,
    /// How often: a count and a unit, `30m`, `6h`, `1d`.
    ///
    /// Held as the string the author wrote rather than as a number of seconds,
    /// because it is also what is shown on the extension's page. Parsed by
    /// [`Scheduled::interval`], and a manifest whose `every` does not parse is
    /// refused rather than rounded to something nobody asked for.
    pub every: String,
}

/// The units an interval may be written in.
///
/// Minutes, hours and days, and deliberately no seconds. **The unit set is the
/// floor**: the shortest interval anybody can express is one minute, so there
/// is no separate minimum to state, document and then disagree with in a second
/// reader. A handler wanting to run more often than a person can notice is a
/// busy loop with extra steps.
///
/// There is no ceiling. `3650d` is silly and harms nothing, and a rule refusing
/// it would be a rule somebody has to learn.
const UNITS: [(char, u64); 3] = [('m', 60), ('h', 60 * 60), ('d', 24 * 60 * 60)];

impl Scheduled {
    /// How often, as a duration, or `None` when `every` is not one.
    ///
    /// [`Manifest::validate`] refuses a manifest this answers `None` for, so a
    /// `None` reaching the clock is a manifest that was never checked rather
    /// than an ordinary state.
    ///
    /// Written with `strip_suffix` rather than by splitting off the last byte:
    /// `every` is a string an author typed, `"1\u{447}"` is three bytes with a
    /// character boundary in the middle of the last two, and `split_at` on a
    /// byte index inside a character panics. A manifest may be wrong; it may
    /// not take the process with it.
    #[must_use]
    pub fn interval(&self) -> Option<std::time::Duration> {
        let (count, seconds) = UNITS.iter().find_map(|(unit, seconds)| {
            self.every
                .strip_suffix(*unit)
                .map(|count| (count, *seconds))
        })?;
        // A leading zero is refused rather than accepted and normalised: `01h`
        // and `1h` would then be two spellings of one interval, and the page
        // shows what the author wrote.
        if count.is_empty()
            || count.starts_with('0')
            || !count.bytes().all(|byte| byte.is_ascii_digit())
        {
            return None;
        }
        count
            .parse::<u64>()
            .ok()?
            .checked_mul(seconds)
            .map(std::time::Duration::from_secs)
    }
}

/// A package, as its manifest states it.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct Manifest {
    /// The format this file is written in. See [`SUPPORTED_MANIFEST_VERSION`].
    pub manifest_version: u32,
    /// Permanent, and the namespace every kind it publishes is prefixed with.
    pub id: String,
    /// The package's own version, which is not the API's and not the app's.
    pub version: String,
    pub name: String,
    #[serde(default)]
    pub summary: String,
    #[serde(default)]
    pub description: String,
    /// A name from the shared icon library.
    #[serde(default)]
    pub icon: Option<String>,
    pub engines: Engines,
    /// Named things the build must be able to do. Checked by the host.
    #[serde(default)]
    pub capabilities: Vec<String>,
    /// Where it may reach, if anywhere.
    ///
    /// Beside [`Manifest::capabilities`] rather than inside it, because the two
    /// answer different questions and a capability is a word. `net` is *may
    /// this package dial out at all*, which is what a card tells a person
    /// before they install; this is *where to*, which is the list the request
    /// is actually checked against. One without the other is refused — see
    /// [`Manifest::validate_running_code`].
    #[serde(default)]
    pub net: Net,
    #[serde(default)]
    pub requires: Requires,
    #[serde(default)]
    pub areas: Vec<Area>,
    /// Paths inside the archive, each a `__type__` definition.
    #[serde(default)]
    pub types: Vec<String>,
    #[serde(default)]
    pub opens: Opens,
    /// Path inside the archive to what an agent is told, if anything.
    #[serde(default)]
    pub prompt: Option<String>,
    #[serde(default)]
    pub dependencies: Dependencies,
    #[serde(default)]
    pub author: Option<Author>,
    #[serde(default)]
    pub license: Option<String>,
    #[serde(default)]
    pub repository: Option<String>,
    /// The built UI bundle, relative to the archive root, or `None`.
    ///
    /// Optional because an extension is not necessarily a screen. One that
    /// publishes only a vocabulary and a prompt has no code to run, and a
    /// default here would make it ship a two-line module that exists to satisfy
    /// this field — a stub whose only reader is the packer. What is declared is
    /// what the package contains.
    #[serde(default)]
    pub ui: Option<String>,
    /// The built stylesheet, relative to the archive root, or `None`.
    ///
    /// A package carries the utility rules its own markup uses, because the
    /// window's stylesheet does not contain them: Tailwind generates only what
    /// it finds in the window's own source, and a package is not in it. Every
    /// utility an extension used and the shell did not happen to use as well
    /// produced no rule at all — silently, so the section read as a redesign
    /// rather than as a missing file.
    ///
    /// It carries no values. Each rule refers to a variable the window defines
    /// on `:root`, so retinting the window retints the extension with nothing
    /// rebuilt, and there is never a second copy of the design to keep in step.
    #[serde(default)]
    pub styles: Option<String>,
    /// The built service module, relative to the archive root, or `None`.
    ///
    /// Where the package's handlers live: what it does when no screen is
    /// mounted. Optional for the same reason [`Manifest::ui`] is, and
    /// independently of it — a package may have a screen and no handlers, or
    /// handlers and no screen, and the second is not a lesser package. Project
    /// memory reaches a project today without a line of it being executed;
    /// nothing about that has to change for it to gain a handler.
    ///
    /// It is read by Rust and never served to the webview. A handler is not
    /// code the window runs, and putting it behind `syncext://` would make it
    /// reachable from a document — which is exactly the reach this design
    /// exists to withhold.
    #[serde(default)]
    pub service: Option<String>,
    /// Handlers called because something happened to the package.
    #[serde(default)]
    pub lifecycle: Lifecycle,
    /// Handlers called because a clock struck.
    ///
    /// A list rather than a map from handler to interval: the same handler on
    /// two intervals is a package saying something confused, and a list makes
    /// that visible as two entries instead of hiding it behind a key that can
    /// only appear once.
    #[serde(default)]
    pub schedule: Vec<Scheduled>,
}

impl Manifest {
    /// Reads a manifest and refuses anything this build cannot honour.
    ///
    /// Order matters: the format version is checked before the fields, so an
    /// extension from the future is told it needs a newer Sync rather than
    /// being told a field name is unknown — which would be true and useless.
    ///
    /// # Errors
    ///
    /// When the JSON is unreadable, when the format is newer than this build
    /// reads, or when a field is missing, unknown or not usable — an id that
    /// could be a path, a version that is not one, a file that climbs out of
    /// the archive, a kind belonging to another extension.
    pub fn parse(source: &[u8]) -> Result<Self, ManifestError> {
        #[derive(Deserialize)]
        struct JustTheVersion {
            #[serde(rename = "manifestVersion")]
            manifest_version: u32,
        }

        let probe: JustTheVersion = serde_json::from_slice(source)?;
        if probe.manifest_version > SUPPORTED_MANIFEST_VERSION {
            return Err(ManifestError::Newer {
                found: probe.manifest_version,
            });
        }

        let manifest: Self = serde_json::from_slice(source)?;
        manifest.validate()?;
        Ok(manifest)
    }

    /// What has to be true of a manifest beyond parsing.
    ///
    /// Each of these is a refusal that would otherwise become a defect much
    /// later and somewhere else: an id with a slash in it escapes the artefact
    /// directory, an unprefixed kind lets one extension define another's data,
    /// and a path that climbs reads a file the archive does not contain.
    /// What the package does with no screen, and what it had to ask for first.
    ///
    /// Its own method rather than three more paragraphs inside
    /// [`Self::validate`], because it is one subject: every rule here is about
    /// code that runs when nobody is looking, and each is a refusal a person
    /// would otherwise meet as behaviour rather than as a sentence.
    fn validate_running_code(&self) -> Result<(), ManifestError> {
        // A package that ships handlers has to ask to be allowed to run them.
        // Not because this build could not tell from the manifest — it plainly
        // can — but because the capability is what a person is shown before
        // they install anything, and a package whose card said nothing about
        // running code would be running code nobody agreed to.
        if self.service.is_some()
            && !self
                .capabilities
                .iter()
                .any(|capability| capability == BACKGROUND_CAPABILITY)
        {
            return Err(ManifestError::Incomplete(format!(
                "the \"{BACKGROUND_CAPABILITY}\" capability: it ships a service module, and running one is something a person agrees to before it is installed"
            )));
        }

        // The same rule again, and a second capability rather than a wider
        // reading of the first: `background` is agreeing that this package runs
        // code, and `schedule` is agreeing that it runs it while nobody is
        // there. A person shown only the first would have agreed to the
        // narrower of two different things.
        if !self.schedule.is_empty()
            && !self
                .capabilities
                .iter()
                .any(|capability| capability == SCHEDULE_CAPABILITY)
        {
            return Err(ManifestError::Incomplete(format!(
                "the \"{SCHEDULE_CAPABILITY}\" capability: it asks for the clock, and running on one when no window is open is something a person agrees to before it is installed"
            )));
        }

        // The network, and the same rule a third time — with the halves
        // checked in both directions, which the other two do not need. A
        // service module is visible in the package whether or not it was
        // declared, so `background` can only be missing; a host list is the
        // permission itself, so a package can also ask for the network and name
        // nowhere to reach, which is an agreement somebody made for nothing.
        let asked_for_the_network = self
            .capabilities
            .iter()
            .any(|capability| capability == NET_CAPABILITY);
        if !self.net.hosts.is_empty() && !asked_for_the_network {
            return Err(ManifestError::Incomplete(format!(
                "the \"{NET_CAPABILITY}\" capability: it names hosts to reach, and reading something nobody in this window wrote is something a person agrees to before it is installed"
            )));
        }
        if asked_for_the_network && self.net.hosts.is_empty() {
            return Err(ManifestError::Incomplete(
                "the hosts it reaches: it asks for the network, and a permission naming nowhere is one nothing can be checked against".to_string(),
            ));
        }
        for host in &self.net.hosts {
            if !is_host(host) {
                return Err(ManifestError::Invalid(format!(
                    "\"{host}\" is not a host: a name like \"api.github.com\", with no scheme, no port, no path and no wildcard"
                )));
            }
        }

        for scheduled in &self.schedule {
            // A package that asks for the clock says what it will do on it.
            // Required now because now is the only time it can be: nothing can
            // install a schedule until the capability ships in this same
            // change, so no package declares one yet — and a field made
            // mandatory after the first one exists breaks it.
            if scheduled.description.trim().is_empty() {
                return Err(ManifestError::Incomplete(format!(
                    "what \"{}\" does: it runs on a clock, and the page a person decides from can say how often on its own but not what for",
                    scheduled.handler
                )));
            }
            if scheduled.interval().is_none() {
                return Err(ManifestError::Invalid(format!(
                    "\"{}\" is not how often to run \"{}\": a count and a unit, like \"30m\", \"6h\" or \"1d\" — minutes, hours or days, and at least one of them",
                    scheduled.every, scheduled.handler
                )));
            }
        }

        Ok(())
    }

    fn validate(&self) -> Result<(), ManifestError> {
        if !is_identifier(&self.id) {
            return Err(ManifestError::Invalid(format!(
                "\"{}\" is not a usable extension id: lowercase letters, digits and hyphens, starting with a letter",
                self.id
            )));
        }
        if !looks_like_a_version(&self.version) {
            return Err(ManifestError::Invalid(format!(
                "\"{}\" is not a version: major.minor.patch, optionally with a pre-release",
                self.version
            )));
        }
        if self.name.trim().is_empty() {
            return Err(ManifestError::Incomplete("a name".to_string()));
        }
        if self.engines.sync_api.trim().is_empty() {
            return Err(ManifestError::Incomplete(
                "the range of Sync's extension API it was written for".to_string(),
            ));
        }

        if !self.areas.is_empty() && self.ui.is_none() {
            return Err(ManifestError::Incomplete(
                "a ui bundle: it declares sections, and a section is drawn by code".to_string(),
            ));
        }

        // The same rule, one occasion over: a package that says when to call a
        // handler and ships nothing to call has declared an intention rather
        // than a capability, and the install that discovers it would be the
        // first thing to find out.
        let named = self.handlers();
        if !named.is_empty() && self.service.is_none() {
            return Err(ManifestError::Incomplete(format!(
                "a service module: it names the handler \"{}\", and a handler is a function in a file",
                named[0]
            )));
        }
        for handler in &named {
            if handler.trim().is_empty() {
                return Err(ManifestError::Invalid(
                    "a handler with no name is named by nothing that could call it".to_string(),
                ));
            }
        }

        for area in &self.areas {
            if !is_identifier(&area.id) {
                return Err(ManifestError::Invalid(format!(
                    "\"{}\" is not a usable area id",
                    area.id
                )));
            }
            if area.label.trim().is_empty() {
                return Err(ManifestError::Incomplete(format!(
                    "a label for the area \"{}\"",
                    area.id
                )));
            }
        }

        for path in self.files() {
            if !is_inside(path) {
                return Err(ManifestError::Invalid(format!(
                    "\"{path}\" is not a path inside the archive"
                )));
            }
        }

        self.validate_running_code()?;

        let prefix = self.kind_prefix();
        for kind in &self.opens.kinds {
            if !kind.starts_with(&prefix) {
                return Err(ManifestError::Invalid(format!(
                    "\"{kind}\" is not this extension's to open: a kind it publishes begins with \"{prefix}\""
                )));
            }
        }

        // The same rule, for the same reason, one field over. A badge is a
        // count drawn on this extension's own row, so a kind in it that belongs
        // to another extension would put somebody else's number in front of a
        // person as if it were this section's to answer for.
        for area in &self.areas {
            let Some(badge) = &area.badge else { continue };
            for kind in &badge.kinds {
                if !kind.starts_with(&prefix) {
                    return Err(ManifestError::Invalid(format!(
                        "the area \"{}\" badges \"{kind}\", which is not this extension's: a kind it publishes begins with \"{prefix}\"",
                        area.id
                    )));
                }
            }
        }

        Ok(())
    }

    /// Every path the manifest points at, in one place.
    ///
    /// One list because three callers want it — validation, extraction and
    /// hashing — and three walks of the same structure is how one of them
    /// forgets the prompt.
    pub fn files(&self) -> Vec<&str> {
        let mut paths: Vec<&str> = Vec::new();
        if let Some(ui) = &self.ui {
            paths.push(ui.as_str());
        }
        if let Some(styles) = &self.styles {
            paths.push(styles.as_str());
        }
        if let Some(service) = &self.service {
            paths.push(service.as_str());
        }
        paths.extend(self.types.iter().map(String::as_str));
        if let Some(prompt) = &self.prompt {
            paths.push(prompt.as_str());
        }
        paths
    }

    /// Every handler the manifest names, in one place.
    ///
    /// Beside [`Self::files`] and for the same reason: the names are what a
    /// module is checked against, and a second walk of the same structure is
    /// how one occasion's handlers get left out of the check. There is
    /// deliberately no `handlers` field listing them — every name arrives
    /// attached to an occasion that will call it, and a second list of the same
    /// names would disagree with the first the day somebody renamed one.
    ///
    /// Names are not prefixed with the extension's id, unlike its kinds. A kind
    /// goes into a corpus everybody shares; a handler's name is only ever read
    /// beside the package that declared it.
    #[must_use]
    pub fn handlers(&self) -> Vec<&str> {
        let mut named: Vec<&str> = Vec::new();
        if let Some(installed) = &self.lifecycle.installed {
            named.push(installed.as_str());
        }
        for scheduled in &self.schedule {
            named.push(scheduled.handler.as_str());
        }
        named
    }

    /// The kinds this extension may publish, by the rule the store enforces.
    #[must_use]
    pub fn kind_prefix(&self) -> String {
        format!("{}.", self.id)
    }
}

/// `records`, `project-memory`, `my-thing-2` — and nothing that could be a path.
///
/// Reachable from [`crate::registry`] as well, which builds a URL and a cache
/// file name out of an id it read from the index. That id came off the network,
/// so it is held to the same rule as one a manifest states rather than to a
/// second spelling of "nothing that could be a path".
pub(crate) fn is_identifier(candidate: &str) -> bool {
    let mut characters = candidate.chars();
    let Some(first) = characters.next() else {
        return false;
    };
    if !first.is_ascii_lowercase() {
        return false;
    }
    candidate.chars().all(|character| {
        character.is_ascii_lowercase() || character.is_ascii_digit() || character == '-'
    }) && !candidate.ends_with('-')
}

/// A version, to the depth worth checking here.
///
/// Not a full semver parse: the host has one — `isVersion`, on the same surface
/// that declares `SYNC_API_VERSION` — and this only has to keep a directory
/// name and a display string from being nonsense.
fn looks_like_a_version(candidate: &str) -> bool {
    let core = candidate
        .split_once('-')
        .map_or(candidate, |(before, _)| before);
    let parts: Vec<&str> = core.split('.').collect();
    parts.len() == 3
        && parts
            .iter()
            .all(|part| !part.is_empty() && part.chars().all(|c| c.is_ascii_digit()))
}

/// Whether a string is a host name and only a host name.
///
/// Deliberately narrower than what a resolver would accept. Everything refused
/// here is a way of writing something that reads as one host and reaches
/// another: a scheme or a path makes the check compare a name against a URL, a
/// port and credentials are not part of a name, `*` is the wildcard this list
/// does not have, and a trailing dot is the same host spelled so that a
/// comparison misses it. An address is refused for a different reason — a
/// package naming a number is one whose permission nobody can read.
fn is_host(candidate: &str) -> bool {
    !candidate.is_empty()
        && candidate.len() <= 253
        && candidate
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '.')
        && candidate.split('.').all(|label| {
            !label.is_empty()
                && !label.starts_with('-')
                && !label.ends_with('-')
                && label.len() <= 63
        })
        && candidate.contains('.')
        && !candidate
            .rsplit('.')
            .next()
            .unwrap_or_default()
            .chars()
            .all(|c| c.is_ascii_digit())
}

/// Whether a path stays inside the archive it came from.
fn is_inside(path: &str) -> bool {
    !path.is_empty()
        && !path.starts_with('/')
        && !path.contains('\\')
        && path
            .split('/')
            .all(|part| !part.is_empty() && part != "." && part != "..")
}

/// The hashes file: every path in the archive and what it should be.
///
/// A `BTreeMap` rather than a `HashMap` because the packer writes this file and
/// a reproducible artefact needs a stable order. Sorting at the point the type
/// is chosen means nobody has to remember to sort before writing.
pub type Hashes = BTreeMap<String, String>;

#[cfg(test)]
mod tests {
    // A test that cannot set itself up has failed, and panicking is the
    // shortest true way to say so.
    #![allow(clippy::expect_used)]

    use super::*;

    fn minimal(extra: &str) -> String {
        format!(
            r#"{{
              "manifestVersion": 1,
              "id": "probe",
              "version": "1.0.0",
              "name": "Probe",
              "engines": {{ "syncApi": "^1.0" }}
              {extra}
            }}"#
        )
    }

    #[test]
    fn a_minimal_manifest_reads() {
        let manifest = Manifest::parse(minimal("").as_bytes()).expect("valid");
        assert_eq!(manifest.id, "probe");
        assert!(
            manifest.ui.is_none(),
            "a package declares the code it ships"
        );
        assert!(manifest.areas.is_empty());
    }

    #[test]
    fn a_package_may_have_handlers_and_no_screen() {
        let manifest = Manifest::parse(
            minimal(
                r#", "capabilities": ["background"],
                   "service": "service/index.js",
                   "lifecycle": { "installed": "probe.installed" }"#,
            )
            .as_bytes(),
        )
        .expect("valid");
        assert!(
            manifest.ui.is_none(),
            "what a package does with no screen is not a lesser package"
        );
        assert_eq!(manifest.handlers(), vec!["probe.installed"]);
        assert!(
            manifest.files().contains(&"service/index.js"),
            "a file the hashes do not cover is a file nothing verified"
        );
    }

    /// Running code with nobody watching is something a person agrees to, and
    /// the card is where they agree to it. A package that ships handlers and
    /// asks for nothing would be running code that was never on the card.
    #[test]
    fn handlers_without_the_capability_are_refused() {
        let error = Manifest::parse(
            minimal(
                r#", "service": "service/index.js",
                   "lifecycle": { "installed": "probe.installed" }"#,
            )
            .as_bytes(),
        )
        .expect_err("it ships handlers and asks for nothing");
        let said = error.to_string();
        assert!(said.contains("background"), "{said}");
        assert!(
            said.contains("agrees to"),
            "the refusal says why it is a capability rather than an inference: {said}"
        );
    }

    #[test]
    fn a_package_declares_where_it_reaches() {
        let manifest = Manifest::parse(
            minimal(r#", "capabilities": ["net"], "net": { "hosts": ["api.github.com"] }"#)
                .as_bytes(),
        )
        .expect("valid");
        assert!(manifest.net.admits("api.github.com"));
        assert!(
            manifest.net.admits("API.GitHub.com"),
            "a host name has no case, and a check that told two spellings apart would refuse a request over the shape of a string"
        );
        assert!(
            !manifest.net.admits("github.com"),
            "the host it named is the host it reaches, and a parent of it is somewhere else"
        );
    }

    /// The other half of [`handlers_without_the_capability_are_refused`], and
    /// the reason is the same one: the card is where a person agrees to this.
    #[test]
    fn hosts_without_the_capability_are_refused() {
        let error =
            Manifest::parse(minimal(r#", "net": { "hosts": ["api.github.com"] }"#).as_bytes())
                .expect_err("it names a host and asks for nothing");
        let said = error.to_string();
        assert!(said.contains("net"), "{said}");
        assert!(said.contains("agrees to"), "{said}");
    }

    /// And the direction the other capabilities cannot be wrong in: a package
    /// may ask for the network and name nowhere, which is a permission with no
    /// extent — nothing to check a request against, and nothing on the card for
    /// a person to have agreed to.
    #[test]
    fn the_capability_without_a_host_is_refused() {
        let error = Manifest::parse(minimal(r#", "capabilities": ["net"]"#).as_bytes())
            .expect_err("it asks for the network and names nowhere");
        assert!(error.to_string().contains("hosts"), "{error}");
    }

    #[test]
    fn a_pattern_is_not_a_host() {
        // Each of these reads as one host and is not one: a wildcard is a
        // family nobody enumerated, and the rest are the spellings that make a
        // comparison against a name answer about something else.
        for written in [
            "*.githubusercontent.com",
            "https://api.github.com",
            "api.github.com/repos",
            "api.github.com:443",
            "user@api.github.com",
            "api.github.com.",
            "localhost",
            "192.168.0.1",
            "",
        ] {
            let error = Manifest::parse(
                minimal(&format!(
                    r#", "capabilities": ["net"], "net": {{ "hosts": ["{written}"] }}"#
                ))
                .as_bytes(),
            )
            .expect_err(written);
            assert!(
                error.to_string().contains("is not a host"),
                "\"{written}\" was admitted as a host: {error}"
            );
        }
    }

    #[test]
    fn a_scheduled_handler_is_one_of_the_package_s_handlers() {
        let manifest = Manifest::parse(
            minimal(
                r#", "capabilities": ["background", "schedule"],
                   "service": "service/index.js",
                   "schedule": [{ "handler": "probe.poll", "description": "Looks for new issues", "every": "6h" }]"#,
            )
            .as_bytes(),
        )
        .expect("valid");
        assert_eq!(
            manifest.handlers(),
            vec!["probe.poll"],
            "every name arrives attached to the occasion that will call it"
        );
        assert_eq!(
            manifest.schedule[0].interval(),
            Some(std::time::Duration::from_hours(6))
        );
    }

    /// `background` says this package runs code; `schedule` says it runs it
    /// while nobody is there. A person shown only the first agreed to the
    /// narrower of two different things.
    #[test]
    fn a_schedule_without_its_own_capability_is_refused() {
        let error = Manifest::parse(
            minimal(
                r#", "capabilities": ["background"],
                   "service": "service/index.js",
                   "schedule": [{ "handler": "probe.poll", "description": "Looks for new issues", "every": "6h" }]"#,
            )
            .as_bytes(),
        )
        .expect_err("it asks for the clock and says nothing about it");
        let said = error.to_string();
        assert!(said.contains("schedule"), "{said}");
        assert!(
            said.contains("no window is open"),
            "the refusal names what is actually being agreed to: {said}"
        );
    }

    /// The same rule the install occasion already has: a package that says
    /// *when* to call a handler and ships nothing to call it in has declared an
    /// intention rather than a capability.
    #[test]
    fn a_schedule_with_no_service_module_is_refused() {
        let error = Manifest::parse(
            minimal(
                r#", "capabilities": ["schedule"],
                   "schedule": [{ "handler": "probe.poll", "description": "Looks for new issues", "every": "6h" }]"#,
            )
            .as_bytes(),
        )
        .expect_err("it names a handler and ships no module");
        assert!(error.to_string().contains("a service module"), "{error}");
    }

    /// The page a person decides from can work out *how often* from `every`
    /// and can work out *what for* from nothing at all. So the package says it.
    #[test]
    fn a_schedule_that_does_not_say_what_it_does_is_refused() {
        let error = Manifest::parse(
            minimal(
                r#", "capabilities": ["background", "schedule"],
                   "service": "service/index.js",
                   "schedule": [{ "handler": "probe.poll", "description": "  ", "every": "6h" }]"#,
            )
            .as_bytes(),
        )
        .expect_err("it asks for the clock and says nothing about what it will do on it");
        let said = error.to_string();
        assert!(
            said.contains("probe.poll"),
            "the refusal names the handler it is about: {said}"
        );
        assert!(
            said.contains("what for"),
            "and says which half of the sentence is missing: {said}"
        );
    }

    #[test]
    fn an_every_that_is_not_an_interval_is_refused() {
        for every in [
            "", "6", "h", "0h", "01h", "6s", "-1h", "6 h", "1.5h", "sixh",
        ] {
            let error = Manifest::parse(
                minimal(&format!(
                    r#", "capabilities": ["background", "schedule"],
                       "service": "service/index.js",
                       "schedule": [{{ "handler": "probe.poll", "description": "Looks for new issues", "every": "{every}" }}]"#
                ))
                .as_bytes(),
            )
            .expect_err("\"{every}\" is not how often to run anything");
            assert!(
                error.to_string().contains("probe.poll"),
                "the refusal names the handler it is about: {error}"
            );
        }
    }

    /// `every` is a string somebody typed, and the last byte of `"1ч"` is in
    /// the middle of a character. Splitting on a byte index there panics, so
    /// the parser strips a suffix instead. A manifest may be wrong; it may not
    /// take the process with it.
    #[test]
    fn an_every_in_another_script_is_refused_rather_than_fatal() {
        let error = Manifest::parse(
            minimal(
                r#", "capabilities": ["background", "schedule"],
                   "service": "service/index.js",
                   "schedule": [{ "handler": "probe.poll", "description": "Looks for new issues", "every": "1ч" }]"#,
            )
            .as_bytes(),
        )
        .expect_err("a unit this build does not know");
        assert!(error.to_string().contains("probe.poll"), "{error}");
    }

    #[test]
    fn an_interval_is_minutes_hours_or_days() {
        let of = |every: &str| {
            Scheduled {
                handler: "probe.poll".to_owned(),
                description: "Looks for new issues".to_owned(),
                every: every.to_owned(),
            }
            .interval()
        };
        assert_eq!(of("30m"), Some(std::time::Duration::from_mins(30)));
        assert_eq!(of("1h"), Some(std::time::Duration::from_hours(1)));
        assert_eq!(of("1d"), Some(std::time::Duration::from_hours(24)));
        assert_eq!(
            of("1m"),
            Some(std::time::Duration::from_mins(1)),
            "the unit set is the floor: a minute is the shortest thing sayable"
        );
        assert_eq!(of("0m"), None, "an interval of nothing is not an interval");
    }

    #[test]
    fn a_package_may_have_a_screen_and_no_handlers() {
        let manifest =
            Manifest::parse(minimal(r#", "ui": "ui/index.js""#).as_bytes()).expect("valid");
        assert!(manifest.service.is_none());
        assert!(manifest.handlers().is_empty());
    }

    /// The mirror of the areas-without-ui refusal: an occasion with nothing to
    /// call is an intention, and the install would be the first to find out.
    #[test]
    fn an_occasion_without_a_module_is_refused() {
        let error = Manifest::parse(
            minimal(r#", "lifecycle": { "installed": "probe.installed" }"#).as_bytes(),
        )
        .expect_err("a handler is a function in a file");
        let said = error.to_string();
        assert!(
            said.contains("service module") && said.contains("probe.installed"),
            "the refusal has to name what was promised: {said}"
        );
    }

    #[test]
    fn a_service_module_may_climb_nowhere() {
        let error = Manifest::parse(
            minimal(
                r#", "service": "../elsewhere/index.js",
                       "lifecycle": { "installed": "probe.installed" }"#,
            )
            .as_bytes(),
        )
        .expect_err("a path that climbs reads a file the archive does not contain");
        assert!(error.to_string().contains("inside the archive"));
    }

    /// A field this build does not know is a typo or a newer format, and both
    /// are better named than ignored — including inside the new object.
    #[test]
    fn an_unknown_occasion_is_named_rather_than_ignored() {
        let error = Manifest::parse(
            minimal(
                r#", "service": "service/index.js",
                       "lifecycle": { "whenever": "probe.someday" }"#,
            )
            .as_bytes(),
        )
        .expect_err("unknown fields are refused");
        assert!(error.to_string().contains("whenever"), "{error}");
    }

    #[test]
    fn a_vocabulary_needs_no_code() {
        let manifest = Manifest::parse(
            minimal(r#", "types": ["types/a.json"], "prompt": "prompt/instructions.md""#)
                .as_bytes(),
        )
        .expect("valid");
        assert_eq!(
            manifest.files(),
            vec!["types/a.json", "prompt/instructions.md"],
            "nothing accounts for a module that is not there"
        );
    }

    #[test]
    fn a_section_without_code_to_draw_it_is_refused() {
        let source =
            minimal(r#", "areas": [{ "id": "probe", "label": "Probe", "frame": "single" }]"#);
        let error = Manifest::parse(source.as_bytes()).expect_err("refused");
        assert!(error.to_string().contains("ui bundle"), "{error}");
    }

    #[test]
    fn a_newer_format_says_so_rather_than_naming_a_field() {
        let source = r#"{ "manifestVersion": 2, "whatever": true }"#;
        let error = Manifest::parse(source.as_bytes()).expect_err("refused");
        assert!(matches!(error, ManifestError::Newer { found: 2 }));
    }

    #[test]
    fn an_unknown_field_is_refused() {
        let error =
            Manifest::parse(minimal(r#", "colour": "red""#).as_bytes()).expect_err("refused");
        assert!(
            error.to_string().contains("colour"),
            "the refusal names the field: {error}"
        );
    }

    #[test]
    fn an_id_that_could_be_a_path_is_refused() {
        let source = minimal("").replace("\"probe\"", "\"../escape\"");
        assert!(Manifest::parse(source.as_bytes()).is_err());
    }

    #[test]
    fn a_file_that_climbs_out_is_refused() {
        let source = minimal(r#", "ui": "../../etc/passwd""#);
        assert!(Manifest::parse(source.as_bytes()).is_err());
    }

    #[test]
    fn opening_another_extensions_kind_is_refused() {
        let source = minimal(r#", "opens": { "kinds": ["records.decision"] }"#);
        let error = Manifest::parse(source.as_bytes()).expect_err("refused");
        assert!(error.to_string().contains("probe."), "{error}");
    }

    #[test]
    fn a_section_badges_what_it_shows_and_nothing_else() {
        let source = minimal(
            r#", "ui": "ui/index.js", "areas": [{ "id": "here", "label": "Here", "frame": "single",
                 "badge": { "kinds": ["probe.finding"], "freshness": ["stale", "invalid"] } }]"#,
        );
        let manifest = Manifest::parse(source.as_bytes()).expect("valid");
        let badge = manifest.areas[0].badge.as_ref().expect("declared");
        assert_eq!(badge.kinds, vec!["probe.finding"]);
        assert_eq!(badge.freshness, vec!["stale", "invalid"]);
    }

    #[test]
    fn a_section_with_no_badge_declares_none_rather_than_an_empty_one() {
        let source = minimal(
            r#", "ui": "ui/index.js", "areas": [{ "id": "here", "label": "Here", "frame": "single" }]"#,
        );
        let manifest = Manifest::parse(source.as_bytes()).expect("valid");
        assert!(
            manifest.areas[0].badge.is_none(),
            "an absent badge and a badge over everything are different claims"
        );
    }

    #[test]
    fn badging_another_extensions_kind_is_refused() {
        let source = minimal(
            r#", "ui": "ui/index.js", "areas": [{ "id": "here", "label": "Here", "frame": "single",
                 "badge": { "kinds": ["records.decision"] } }]"#,
        );
        let error = Manifest::parse(source.as_bytes()).expect_err("refused");
        assert!(error.to_string().contains("probe."), "{error}");
        assert!(
            error.to_string().contains("here"),
            "the refusal names the area it is about: {error}"
        );
    }

    #[test]
    fn every_path_it_points_at_is_listed_once() {
        let source = minimal(
            r#", "ui": "ui/index.js", "types": ["types/a.json", "types/b.json"], "prompt": "prompt/instructions.md""#,
        );
        let manifest = Manifest::parse(source.as_bytes()).expect("valid");
        assert_eq!(
            manifest.files(),
            vec![
                "ui/index.js",
                "types/a.json",
                "types/b.json",
                "prompt/instructions.md"
            ]
        );
    }

    #[test]
    fn a_version_that_is_not_one_is_refused() {
        assert!(
            Manifest::parse(minimal("").replace("\"1.0.0\"", "\"latest\"").as_bytes()).is_err()
        );
        assert!(looks_like_a_version("1.2.3"));
        assert!(looks_like_a_version("1.2.3-beta.1"));
        assert!(!looks_like_a_version("1.2"));
    }
}
