//! What a package publishes into a project's memory, and what it tells an agent.
//!
//! Both are files inside the artefact rather than anything the window holds,
//! which is the whole point of the migration this module was written for: the
//! shell used to carry a constant naming every extension and every type it
//! brought, so a project could only be composed of what the build happened to
//! contain. Now the vocabulary travels in the package.
//!
//! They are read here rather than in the window for one reason: the window has
//! no way to read a file out of an artefact that does not involve widening the
//! webview's `connect-src` to reach `syncext://`. Reading them in Rust keeps the
//! policy where it is and works for a package that has no code at all — which
//! is exactly the case a vocabulary-only extension is.
//!
//! **Unknown fields are refused**, for the same reason [`crate::manifest`]
//! refuses them: these files are generated by a tool, so a field nobody
//! recognises is a typo or a newer format, and a typo that is silently dropped
//! becomes a type missing a declaration nobody can see. The engine validates
//! what a well-formed declaration *means*; this only insists that nothing in
//! the file went unread.

use std::path::Path;

use serde::{Deserialize, Serialize};
use serde_json::{Map, Value};

use crate::manifest::Manifest;

/// Something wrong with what a package publishes, in words a person can act on.
#[derive(Debug, thiserror::Error)]
pub enum VocabularyError {
    #[error("the package names \"{path}\" and it could not be read: {source}")]
    Unreadable {
        path: String,
        source: std::io::Error,
    },
    #[error("\"{path}\" is not a readable type definition: {source}")]
    Unparsable {
        path: String,
        source: serde_json::Error,
    },
    #[error(
        "\"{kind}\" in \"{path}\" is not this extension's to publish: a kind it publishes begins with \"{prefix}\""
    )]
    Foreign {
        path: String,
        kind: String,
        prefix: String,
    },
}

/// One type a package publishes, as the engine's schema asks for it.
///
/// The shape is the engine's rather than a shape of ours translated on the way:
/// the window forwards this to `memory_extension_types_publish` unchanged, so
/// there is one spelling of a type definition between the file an author writes
/// and the transaction the engine runs. A second spelling in between is how a
/// definition ends up depending on which of two writers produced it.
///
/// `fields` and `relationships` are carried rather than described, because what
/// makes a declaration well formed is the engine's schema and a second opinion
/// here would be one more thing to keep in step with an engine release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct TypeDefinition {
    /// Prefixed with the extension's id, so two extensions cannot define the
    /// same kind differently.
    pub kind: String,
    pub title: String,
    #[serde(default)]
    pub description: String,
    /// A name from the shared icon library, as the shell spells icon names.
    #[serde(default)]
    pub icon: String,
    /// Declarations by field name, as the engine's schema spells them.
    #[serde(default)]
    pub fields: Map<String, Value>,
    /// Relations by name: `{target, description}`, where `target` is a kind or
    /// `any`.
    #[serde(default)]
    pub relationships: Map<String, Value>,
    /// What an agent reads before writing a record of this type.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub guidance: Option<String>,
}

/// Every type the manifest names, in the order it names them.
///
/// The kind prefix is enforced here rather than trusted, and it is the same
/// rule [`Manifest`] applies to `opens.kinds`: an extension that could publish
/// an unprefixed kind could redefine another extension's data, and the refusal
/// is worth having before anything is written into a repository.
///
/// # Errors
///
/// When a file the manifest names is missing or unreadable, when it is not a
/// well-formed definition, or when it publishes a kind belonging to somebody
/// else.
pub fn read_types(
    root: &Path,
    manifest: &Manifest,
) -> Result<Vec<TypeDefinition>, VocabularyError> {
    let prefix = manifest.kind_prefix();
    let mut published = Vec::with_capacity(manifest.types.len());

    for path in &manifest.types {
        let bytes =
            std::fs::read(root.join(path)).map_err(|source| VocabularyError::Unreadable {
                path: path.clone(),
                source,
            })?;
        let definition: TypeDefinition =
            serde_json::from_slice(&bytes).map_err(|source| VocabularyError::Unparsable {
                path: path.clone(),
                source,
            })?;
        if !definition.kind.starts_with(&prefix) {
            return Err(VocabularyError::Foreign {
                path: path.clone(),
                kind: definition.kind,
                prefix,
            });
        }
        published.push(definition);
    }

    Ok(published)
}

/// What the package tells an agent, whole, or `None` when it says nothing.
///
/// Read as text rather than parsed: it is prose, it is written as prose, and
/// the only thing done to it is writing it into the project's own record so
/// that the MCP server — a process with no view of any of this — can serve it.
///
/// # Errors
///
/// When the manifest names a prompt and the file is not there.
pub fn read_prompt(root: &Path, manifest: &Manifest) -> Result<Option<String>, VocabularyError> {
    let Some(path) = &manifest.prompt else {
        return Ok(None);
    };
    std::fs::read_to_string(root.join(path))
        .map(Some)
        .map_err(|source| VocabularyError::Unreadable {
            path: path.clone(),
            source,
        })
}

#[cfg(test)]
mod tests {
    // A test that cannot set itself up has failed, and panicking is the
    // shortest true way to say so.
    #![allow(clippy::expect_used)]

    use super::*;

    fn manifest(extra: &str) -> Manifest {
        let source = format!(
            r#"{{
              "manifestVersion": 1,
              "id": "probe",
              "version": "1.0.0",
              "name": "Probe",
              "engines": {{ "syncApi": "^1.0" }}
              {extra}
            }}"#
        );
        Manifest::parse(source.as_bytes()).expect("valid")
    }

    fn folder(files: &[(&str, &str)]) -> tempfile::TempDir {
        let root = tempfile::tempdir().expect("a directory");
        for (path, content) in files {
            let at = root.path().join(path);
            if let Some(parent) = at.parent() {
                std::fs::create_dir_all(parent).expect("a parent");
            }
            std::fs::write(at, content).expect("writes");
        }
        root
    }

    const DECISION: &str = r#"{
      "kind": "probe.decision",
      "title": "Decision",
      "description": "A choice that was made.",
      "icon": "signpost",
      "relationships": { "references": { "target": "any", "description": "…" } }
    }"#;

    #[test]
    fn a_definition_is_read_as_the_engine_asks_for_it() {
        let root = folder(&[("types/decision.json", DECISION)]);
        let published = read_types(
            root.path(),
            &manifest(r#", "types": ["types/decision.json"]"#),
        )
        .expect("reads");

        assert_eq!(published.len(), 1);
        assert_eq!(published[0].kind, "probe.decision");
        assert_eq!(published[0].title, "Decision");
        assert!(
            published[0].fields.is_empty(),
            "declaring none is an answer"
        );
        assert!(published[0].relationships.contains_key("references"));
    }

    #[test]
    fn publishing_another_extensions_kind_is_refused() {
        let foreign = DECISION.replace("probe.decision", "records.decision");
        let root = folder(&[("types/decision.json", &foreign)]);
        let error = read_types(
            root.path(),
            &manifest(r#", "types": ["types/decision.json"]"#),
        )
        .expect_err("refused");

        assert!(error.to_string().contains("probe."), "{error}");
    }

    #[test]
    fn an_unknown_field_is_refused_rather_than_dropped() {
        let mistyped = DECISION.replace("\"icon\"", "\"ikon\"");
        let root = folder(&[("types/decision.json", &mistyped)]);
        let error = read_types(
            root.path(),
            &manifest(r#", "types": ["types/decision.json"]"#),
        )
        .expect_err("refused");

        assert!(
            error.to_string().contains("ikon"),
            "it names the field: {error}"
        );
    }

    #[test]
    fn a_named_file_that_is_not_there_is_named_in_the_refusal() {
        let root = folder(&[]);
        let error = read_types(root.path(), &manifest(r#", "types": ["types/gone.json"]"#))
            .expect_err("refused");

        assert!(error.to_string().contains("types/gone.json"), "{error}");
    }

    #[test]
    fn a_package_with_nothing_to_say_says_nothing() {
        let root = folder(&[]);
        assert!(
            read_prompt(root.path(), &manifest(""))
                .expect("reads")
                .is_none()
        );
        assert!(
            read_types(root.path(), &manifest(""))
                .expect("reads")
                .is_empty()
        );
    }

    #[test]
    fn a_prompt_is_carried_whole() {
        let root = folder(&[("prompt/instructions.md", "# Write it down\n")]);
        let prompt = read_prompt(
            root.path(),
            &manifest(r#", "prompt": "prompt/instructions.md""#),
        )
        .expect("reads");

        assert_eq!(prompt.as_deref(), Some("# Write it down\n"));
    }
}
