// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  ShellText = 1,
  Line = 2,
  Step = 3,
  Shell = 4,
  Bang = 5,
  Address = 6,
  At = 7,
  Name = 8,
  Arg = 9,
  SyncAddress = 10,
  FilePath = 11,
  Quoted = 12,
  Word = 13,
  Dashes = 14,
  Words = 15,
  Then = 16
