// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {shellText} from "./console-tokens"
export const parser = LRParser.deserialize({
  version: 14,
  states: "#`QnQQOOOuQRO'#C`OOQO'#Ci'#CiOOQO'#Ce'#CeOOQO'#Cm'#CmO!QQQO'#CkO![QQO'#CbOOQO'#C_'#C_O!gQQO'#CnQ!qQQOOQ!qQQOOOOQO,58z,58zOOQO-E6k-E6kOOQO'#Cd'#CdO!vQQO,58|OOQO,59Y,59YOOQO-E6l-E6lO#QQQO1G.h",
  stateData: "#e~OeOS~OTPOVUOYROZRO[RO^ROfQO~O`WO~PVOPZO`SXcSX~O`_Xc_X~P]Of]O`UXcUX~O`bXcbX~PVO`WO~O`UacUa~P]O`UicUi~P]O`ZVTYf^f~",
  goto: "!ccPPPdjPjPnqPPPxPjP!P![QYOR_WTVOWR^UZSOTW^aZROTW^aSTOWS[TaRa^SXOYR`X",
  nodeNames: "⚠ ShellText Line Step Shell Bang Address At Name Arg SyncAddress FilePath Quoted Word Dashes Words Then",
  maxTerm: 22,
  skippedNodes: [0],
  repeatNodeCount: 2,
  tokenData: "6Q~RfOX!gXY$WYZ$WZ]!g]^$W^p!gpq$Wqr$irs%`sw!gwx'Qx}!g}!O(m!O!P!g!P!Q*e!Q!b!g!b!c-W!c#g!g#g#h-}#h;'S!g;'S;=`$Q<%lO!g~!lYf~OX!gZ]!g^p!gqr!gsw!gx}!g}!O#[!O;'S!g;'S;=`$Q<%lO!g~#_ZOX!gZ]!g^p!gqr!gsw!gx}!g}!O#[!O!`!g!a;'S!g;'S;=`$Q<%lO!g~$TP;=`<%l!g~$]Se~XY$WYZ$W]^$Wpq$W~$pYT~f~OX!gZ]!g^p!gqr!gsw!gx}!g}!O#[!O;'S!g;'S;=`$Q<%lO!g~%eV[~Or%`rs%zs#O%`#O#P&P#P;'S%`;'S;=`&z<%lO%`~&PO[~~&SRO;'S%`;'S;=`&];=`O%`~&bW[~Or%`rs%zs#O%`#O#P&P#P;'S%`;'S;=`&z;=`<%l%`<%lO%`~&}P;=`<%l%`~'VV[~Ow'Qwx%zx#O'Q#O#P'l#P;'S'Q;'S;=`(g<%lO'Q~'oRO;'S'Q;'S;=`'x;=`O'Q~'}W[~Ow'Qwx%zx#O'Q#O#P'l#P;'S'Q;'S;=`(g;=`<%l'Q<%lO'Q~(jP;=`<%l'Q~(r[^~OX!gZ]!g^p!gqr!gsw!gx}!g}!O)h!O!`!g!`!a*`!a;'S!g;'S;=`$Q<%lO!g~)mZ^~OX!gZ]!g^p!gqr!gsw!gx}!g}!O)h!O!`!g!a;'S!g;'S;=`$Q<%lO!g~*eO`~~*l[Z~f~OX*eZ]*e^p*eqr*ers+bsw*ewx+bx}*e}!O,P!O;'S*e;'S;=`-Q<%lO*e~+gUZ~OX+bZ]+b^p+bq;'S+b;'S;=`+y<%lO+b~+|P;=`<%l+b~,U^Z~OX*eZ]*e^p*eqr*ers+bsw*ewx+bx}*e}!O,P!O!`*e!`!a+b!a;'S*e;'S;=`-Q<%lO*e~-TP;=`<%l*e~-_YV~f~OX!gZ]!g^p!gqr!gsw!gx}!g}!O#[!O;'S!g;'S;=`$Q<%lO!g~.S[f~OX!gZ]!g^p!gqr!gsw!gx}!g}!O#[!O#m!g#m#n.x#n;'S!g;'S;=`$Q<%lO!g~.}[f~OX!gZ]!g^p!gqr!gsw!gx}!g}!O#[!O#b!g#b#c/s#c;'S!g;'S;=`$Q<%lO!g~/x[f~OX!gZ]!g^p!gqr!gsw!gx}!g}!O#[!O#V!g#V#W0n#W;'S!g;'S;=`$Q<%lO!g~0s[f~OX!gZ]!g^p!gqr!gsw!gx}!g}!O#[!O![!g![!]1i!];'S!g;'S;=`$Q<%lO!g~1n[f~OX!gZ]!g^p!gqr!gsw!gx}!g}!O#[!O!P!g!P!Q2d!Q;'S!g;'S;=`$Q<%lO!g~2i[f~OX!gZ]!g^p!gqr!gsw!gx}!g}!O#[!O!P!g!P!Q3_!Q;'S!g;'S;=`$Q<%lO!g~3f[Y~f~OX3_Z]3_^p3_qr3_rs4[sw3_wx4[x}3_}!O4y!O;'S3_;'S;=`5z<%lO3_~4aUY~OX4[Z]4[^p4[q;'S4[;'S;=`4s<%lO4[~4vP;=`<%l4[~5O^Y~OX3_Z]3_^p3_qr3_rs4[sw3_wx4[x}3_}!O4y!O!`3_!`!a4[!a;'S3_;'S;=`5z<%lO3_~5}P;=`<%l3_",
  tokenizers: [shellText, 0],
  topRules: {"Line":[0,2]},
  tokenPrec: 104
})
